name: Run lighthouse CI When Push
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Print github workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages ci
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli
          lhci autorun || echo "LHCI failed!"

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('${{ github.workspace }}/lhci_reports/manifest.json'));
            let comments = "";

            results.forEach((result) => {
              const { summary, jsonPath } = result;

              const details = JSON.parse(fs.readFileSync(jsonPath));
              const { audits } = details;

              const formatResult = (res) => Math.round(res * 100);

              Object.keys(summary).forEach(
                (key) => (summary[key] = formatResult(summary[key]))
              );
            });

            const score = (res) => (res >= 90 ? "🟢" : res >= 50 ? "🟠" : "🔴");

            const comment = [
              `⚡️ Lighthouse report!`,
              `| Category | Score |`,
              `| --- | --- |`,
              `| ${score(summary.performance)} Performance | ${summary.performance} |`
            ].join("\n");

            const detail = [
              `| Category | Score |`,
              `| --- | --- |`,
              `| ${score(
                audits["first-contentful-paint"].score * 100
              )} First Contentful Paint | ${
                audits["first-contentful-paint"].displayValue
              } |`
            ].join("\n");

            comments += comment + "\n" + detail + "\n";

            console.log('comment',comment);
            console.log('detail',detail);
            console.log('comments',comments);
            core.setOutput('comments', comments);

      - name: comment PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.format_lighthouse_score.outputs.comments}}
